### ISSUE TITLE
[Bug] inappropriate ioctl for device

### ISSUE THREAD

**Issue by onlyJinx** [comzyh/clash#14]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

release最新版(20210310)

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
clash@debian:~$ cat config.yaml
mixed-port: 1080
allow-lan: true
external-controller: 127.0.0.1:9090
secret: ''
tun:
  enable: true
  device-url: dev://ctun
  device-url: fd://5
  dns-listen: 0.0.0.0:53
dns:
  enable: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16

  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com

  nameserver:
    - 114.114.114.114
    - 8.8.8.8
    - tls://dns.rubyfish.cn:853
    - https://1.1.1.1/dns-query

  fallback:
    - tcp://1.1.1.1
proxies:
...
proxy-groups:
...
rules:
- GEOIP,CN,DIRECT
- MATCH,Proxy
```

### Clash log

```shell
clash@debian:~$ ./clash-linux-amd64 -d .
INFO[0000] Start initial compatible provider Proxy
ERRO[0000] Start Tun interface error: can't open tun: inappropriate ioctl for device
INFO[0000] Mixed(http+socks5) proxy listening at: :1080
INFO[0000] RESTful API listening at: 127.0.0.1:9090
```

### Description

我对着[教程](https://comzyh.gitbook.io/clash/#linux-shi-yong) 敲命令，启动clash时提示标题里的报错(运行的用户也是clash)，可以麻烦帮我看看是哪一部出问题了吗？我的输入顺序如下

ip tuntap add mode tun user clash name ctun
ifconfig ctun up
route add -net 198.18.0.0/16 dev ctun

ipconfig运行结果如下
```
root@debian:~# ifconfig
ctun: flags=4241<UP,POINTOPOINT,NOARP,MULTICAST>  mtu 1500
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 500  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ens33: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.2.131  netmask 255.255.255.0  broadcast 192.168.2.255
        inet6 fe80::20c:29ff:fe3f:b2ca  prefixlen 64  scopeid 0x20<link>
        ether 00:0c:29:3f:b2:ca  txqueuelen 1000  (Ethernet)
        RX packets 32177  bytes 44616187 (42.5 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 8313  bytes 608868 (594.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
路由表

```
root@debian:~# route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         192.168.2.2     0.0.0.0         UG    0      0        0 ens33
192.168.2.0     0.0.0.0         255.255.255.0   U     0      0        0 ens33
198.18.0.0      0.0.0.0         255.255.0.0     U     0      0        0 ctun
```
